-- table for test.

CREATE TABLE stryker (
  id INT NOT NULL primary key,
  description varchar(70) DEFAULT NULL
);

CREATE TABLE strykerAutoIncrement (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  description varchar(70) DEFAULT NULL
);

INSERT INTO stryker VALUES  (1, 'Tools to help automated tests in java');